# Generated by Django 2.0.3 on 2018-05-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20180406_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='video_file',
            field=models.FileField(default='', max_length=200, upload_to='video/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default='', max_length=200, upload_to='mp3/'),
        ),
    ]
